--- Makefile.orig	2019-10-15 22:37:51.000000000 +0200
+++ Makefile	2019-10-15 22:33:50.000000000 +0200
@@ -179,7 +179,7 @@
 # these flags do NOT contain the libraries, to make them easier to overwrite
 COQFLAGS?=-q $(OTHERFLAGS) $(COQEXTRAFLAGS)
 COQCHKFLAGS?=-silent -o $(COQCHKEXTRAFLAGS)
-COQDOCFLAGS?=-interpolate -utf8 $(COQDOCEXTRAFLAGS)
+COQDOCFLAGS?=-interpolate -utf8 --parse-comments --coqlib https://coq.inria.fr/distrib/current/stdlib/ --external https://math-comp.github.io/htmldoc/ mathcomp $(COQDOCEXTRAFLAGS)
 
 COQDOCLIBS?=$(COQLIBS_NOML)
 
@@ -422,6 +422,9 @@
 	$(HIDE)mkdir -p html
 	$(HIDE)$(COQDOC) \
 		-toc $(COQDOCFLAGS) -html $(GAL) $(COQDOCLIBS) -d html $(VFILES)
+# Prosa hack: let's tweak the style a bit
+	$(HIDE)sed -i.bak "s/#90bdff/#eeeeee/" html/coqdoc.css
+	$(HIDE)rm html/coqdoc.css.bak
 
 mlihtml: $(MLIFILES:.mli=.cmi)
 	$(SHOW)'CAMLDOC -d $@'
@@ -446,6 +449,9 @@
 		-toc $(COQDOCFLAGS) -pdf $(GAL) $(COQDOCLIBS) \
 		-o $@ `$(COQDEP) -sort -suffix .v $(VFILES)`
 
+# Prosa: include pretty documentation targets
+include scripts/coqdocjs/Makefile.coqdocjs
+
 # FIXME: not quite right, since the output name is different
 gallinahtml: GAL=-g
 gallinahtml: html
@@ -585,6 +591,17 @@
 	$(HIDE)rm -f $(CMOFILES:%.cmo=%.cmx)
 .PHONY: archclean
 
+vacuum:: cleanall
+	$(SHOW)'VACUUMING *.vo *.glob .*.aux <empty directories>'
+	$(HIDE)find . -depth \( -iname '*.vo' -or  -iname '*.glob' -or -iname '.*.aux' \)  ! -path './.git/*' -delete
+	$(HIDE)find . -depth -type d -empty ! -path './.git/*' -delete
+
+macos-clean::
+	$(SHOW)'CLEAN .DS_Store'
+	$(HIDE)find . -depth -iname '.DS_Store' ! -path './.git/*' -delete
+
+spell::
+	./scripts/flag-typos-in-comments.sh `find .  -iname '*.v' ! -path './classic/*'`

 # Compilation rules ###########################################################
 
